pipeline:
  build:
    image: node:latest
    commands: npm install
  test:
    image: node:latest
    commands: npm run test
  trigger:
    event:
    - push
    - pull_request
    - tag
    - promote
    - rollback    
